### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by techtonik** [dariusbakunas/rawdisk#30]
0.1.2 was [released a year ago](https://github.com/dariusbakunas/rawdisk/releases). It worth to take another snapshot and make sure everything still works.

**Comment by dariusbakunas** [comment]
Sorry, I haven't been working on this for a long time, just don't have as much time as I used to. It is one of my unfinished experiments, not sure when I will be able to get back to it :) feel free to make a fork.

**Comment by techtonik** [comment]
It would be easier to fork and modify if master HEAD was working.

**Comment by dariusbakunas** [comment]
Fixed
